#!/bin/bash

set -e

APP_NAME="$(grep 'app:' mix.exs | sed -e 's/\[//g' -e 's/ //g' -e 's/app://' -e 's/[:,]//g')"
APP_VSN="$(grep 'version:' mix.exs | cut -d '"' -f2)"
TAR_FILENAME=${APP_NAME}-${APP_VSN}.tar.gz
HOST="do"

bold_echo() {
  echo -e "\033[1m---> $1\033[0m"
}

deploy_release() {
  bold_echo "Creating directory if not exist..."
  ssh $HOST mkdir -p $APP_NAME/releases/$APP_VSN

  bold_echo "Copying release to remote..."
  scp $TAR_FILENAME do:~/$APP_NAME/releases/$TAR_FILENAME
  ssh $HOST tar -xzf $APP_NAME/releases/$TAR_FILENAME -C $APP_NAME/

  bold_echo "Waiting for existing application to stop..."
  # Stop existing application if any
  ssh $HOST $APP_NAME/bin/$APP_NAME stop

  set +e
  # Waiting for application to stop
  ssh $HOST $APP_NAME/bin/$APP_NAME pid
  while [ $? -ne 1 ]
  do
    ssh $HOST $APP_NAME/bin/$APP_NAME pid
  done

  bold_echo "Starting application in daemon mode..."
  ssh $HOST "source $APP_NAME/.env  && $APP_NAME/bin/$APP_NAME daemon"

  bold_echo "Health checking application..."
  # Waiting for application to start
  ssh $HOST "$APP_NAME/bin/$APP_NAME rpc 'IO.puts(\"health-check\")'"
  while [ $? -ne 0 ]
  do
    ssh $HOST "$APP_NAME/bin/$APP_NAME rpc 'IO.puts(\"health-check\")'"
  done
  set -e
  bold_echo "Application started!"

  bold_echo "Removing remote tar file..."
  ssh $HOST rm "~/$APP_NAME/releases/$TAR_FILENAME"

  bold_echo "Removing local tar file..."
  rm $TAR_FILENAME
}

# buildkite-agent artifact download $TAR_FILENAME .
deploy_release

