steps:
  # - label: ":hammer: Tests"
  #   command: "mix deps.get && mix test --exclude integration"

  # - wait

  - label: ":package: Build Release"
    command: "./build"
    artifact_paths:
      - "*.tar.gz"

  - block: "Deploy"
    prompt: "Deploy to production?"

  - label: "🚀"
    command: "./deploy"
    if: build.branch == 'master'
    concurrency_group: "my-app-deploy"
    concurrency: 1
