name: Elixir CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - run: mix ecto.setup
      - run: mix deps.get
      - run: mix test --exclude integration
